trigger:
  batch: true
  branches:
   include:
    - master
    - azure-pipelines

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: Project.Name
    value: restaurant

stages:
  - template: templates/master.yaml@templates
