trigger:
  batch: true
  branches:
   include:
    - master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Pipeline
  - name: Project.Name
    value: restaurant

stages:
  - template: templates/master.yaml
